local map = vim.keymap.set

map('n', '<Esc>', '<cmd>nohlsearch<CR>', { desc = 'Clear search highlight' })
map('n', '<leader>e', '<cmd>Neotree toggle left<CR>', { desc = 'Toggle file tree' })
map('n', '<leader>E', '<cmd>Neotree float reveal<CR>', { desc = 'Reveal in floating tree' })
map('n', '<leader>gg', '<cmd>Neotree git_status right<CR>', { desc = 'Git status tree' })
map('n', '<leader>ff', function()
  require('telescope.builtin').find_files({ hidden = true })
end, { desc = 'Find files' })
map('n', '<leader>fg', function()
  require('telescope.builtin').live_grep()
end, { desc = 'Live grep' })
map('n', '<leader>fb', function()
  require('telescope.builtin').buffers()
end, { desc = 'Find buffers' })
map('n', '<leader>fh', function()
  require('telescope.builtin').help_tags()
end, { desc = 'Search help tags' })
